name: test_flutter
description: A new Flutter project.

# A version number is required for publishing, remove this line before publishing.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_b.png
  #   - images/a_dot_b.png
  # A description of the changes made in this version:
  uses-material-design: true
