from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "c3_rnt2_ai" / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from c3rnt2.control_plane.app import create_control_app
from c3rnt2.control_plane.dependencies import ControlDependencies


class _StubState:
    api_url = "http://127.0.0.1:8000"
    _active_run_id = None

    def status(self): return {"ok": True}
    def start_bootstrap(self, **_kwargs): return {"ok": True}
    def restart_runtime(self): return {"ok": True}
    def get_allowlist(self): return []
    def set_allowlist(self, domains): return domains
    def start_training(self, *_args, **_kwargs): return {"ok": True}
    def reset_training_state(self, **_kwargs): return {"ok": True}
    def list_runs(self, **_kwargs): return []
    def get_run(self, *_args, **_kwargs): return None
    def get_run_events(self, *_args, **_kwargs): return []
    def get_run_logs(self, *_args, **_kwargs): return {}
    def _build_training_stream_payload(self): return {"ts": 0.0}
    def runtime_status(self): return {"ok": True}
    def autonomy_status(self, **_kwargs): return {"enabled": False, "boot_mode": "manual", "state": "idle", "active_agents": [], "autoedit_scope": "safe"}
    def start_autonomy(self): return {"ok": True}
    def stop_autonomy(self): return {"ok": True}
    def configure_autonomy(self, _payload): return {"ok": True}
    def _latest_autonomy_events(self, **_kwargs): return []
    def voice_status(self): return {"ok": True}
    def restart_voice(self): return {"ok": True}
    def obsidian_status(self): return {"ok": True}
    def configure_obsidian(self, _payload): return {"ok": True}
    def multimodal_status(self): return {"ok": True}


CONTROL_TS_IMPORTS = [
    "AutonomyEvent",
    "AutonomyStatus",
    "ControlStatus",
    "MultimodalStatus",
    "TrainingRunSummary",
]

CONTROL_RESPONSE_TYPES = {
    ("GET", "/healthz"): "HealthResponse",
    ("GET", "/control/status"): "ControlStatus",
    ("POST", "/control/bootstrap"): "BootstrapResponse",
    ("POST", "/control/model/init"): "InitModelResponse",
    ("POST", "/control/runtime/restart"): "OkResponse",
    ("POST", "/control/instructions/reload"): "OkResponse",
    ("GET", "/control/internet/allowlist"): "AllowlistResponse",
    ("POST", "/control/internet/allowlist"): "AllowlistResponse",
    ("GET", "/control/voice/status"): "VoiceStatusResponse",
    ("POST", "/control/voice/restart"): "VoiceStatusResponse",
    ("GET", "/control/obsidian/status"): "ObsidianStatusResponse",
    ("POST", "/control/obsidian/config"): "ObsidianConfigResponse",
    ("GET", "/control/multimodal/status"): "ControlMultimodalStatusResponse",
    ("GET", "/control/multimodal/stream"): "MultimodalStreamResponse",
    ("POST", "/control/training/start"): "TrainingStartResponse",
    ("POST", "/control/training/reset"): "TrainingResetResponse",
    ("GET", "/control/training/runs"): "TrainingRunsResponse",
    ("GET", "/control/training/runs/{run_id}"): "TrainingRunResponse",
    ("GET", "/control/training/runs/{run_id}/events"): "TrainingRunEventsResponse",
    ("GET", "/control/training/runs/{run_id}/logs"): "TrainingRunLogsResponse",
    ("GET", "/control/training/stream"): "TrainingStreamResponse",
    ("GET", "/control/autonomy/status"): "ControlAutonomyStatusResponse",
    ("POST", "/control/autonomy/start"): "AutonomyToggleResponse",
    ("POST", "/control/autonomy/stop"): "AutonomyToggleResponse",
    ("POST", "/control/autonomy/config"): "AutonomyConfigResponse",
    ("GET", "/control/autonomy/stream"): "AutonomyStreamResponse",
}

CONTROL_REQUEST_TYPES = {
    ("POST", "/control/bootstrap"): "BootstrapRequest",
    ("POST", "/control/internet/allowlist"): "AllowlistRequest",
    ("POST", "/control/obsidian/config"): "ObsidianConfigRequest",
    ("POST", "/control/training/start"): "TrainingStartRequest",
    ("POST", "/control/training/reset"): "TrainingResetRequest",
    ("POST", "/control/autonomy/config"): "AutonomyConfigRequest",
}


def _render_control_ts(openapi: dict) -> str:
    paths = openapi.get("paths", {})
    lines: list[str] = [
        "// Generated by scripts/export_contracts.py. Do not edit by hand.",
        "import type {",
        *[f"  {name}," for name in CONTROL_TS_IMPORTS],
        "} from \"./types\";",
        "",
        "export type JsonRecord = Record<string, unknown>;",
        "export interface OkResponse { ok: boolean; [key: string]: unknown }",
        "export interface HealthResponse extends OkResponse { service?: string; ts?: number }",
        "export interface BootstrapRequest { force?: boolean; mode?: \"ensure\" | \"rebuild\" | string }",
        "export interface BootstrapResponse extends OkResponse { started?: boolean; reason?: string; mode?: string; stage?: string; log_path?: string }",
        "export interface InitModelResponse extends OkResponse { started?: boolean }",
        "export interface AllowlistRequest { domains: string[] }",
        "export interface AllowlistResponse extends OkResponse { domains: string[] }",
        "export interface VoiceStatusResponse extends OkResponse { [key: string]: unknown }",
        "export interface ObsidianStatusResponse extends OkResponse { [key: string]: unknown }",
        "export interface ObsidianConfigRequest { enabled?: boolean; vault_path?: string }",
        "export interface ObsidianConfigResponse extends OkResponse { config?: JsonRecord; status?: ObsidianStatusResponse }",
        "export interface ControlMultimodalStatusResponse extends OkResponse { status: MultimodalStatus }",
        "export interface TrainingStartRequest { mode: \"quick\" | \"full\" | string; source?: string }",
        "export interface TrainingStartResponse extends OkResponse { run_id?: string; status?: string; queue_reason?: string | null; reused?: boolean; error?: string }",
        "export interface TrainingResetRequest { clear_runs?: boolean; clear_learning_queue?: boolean }",
        "export interface TrainingResetResponse extends OkResponse { removed_runs?: number; runs?: TrainingRunSummary[]; autonomy?: AutonomyStatus }",
        "export interface TrainingRunsResponse extends OkResponse { runs: TrainingRunSummary[] }",
        "export interface TrainingRunResponse extends OkResponse { run: TrainingRunSummary }",
        "export interface TrainingRunEventsResponse extends OkResponse { run_id: string; events: NonNullable<TrainingRunSummary[\"events\"]> }",
        "export interface TrainingRunLogsResponse extends OkResponse { run_id: string; logs: Record<string, string[]> }",
        "export interface TrainingStreamResponse { ts: number; [key: string]: unknown }",
        "export interface ControlAutonomyStatusResponse extends OkResponse { autonomy: AutonomyStatus }",
        "export interface AutonomyToggleResponse extends OkResponse { enabled?: boolean }",
        "export interface AutonomyConfigRequest { enabled?: boolean; reflection_enabled?: boolean; training_enabled?: boolean; autoedit_enabled?: boolean; multi_agent_dialogue_enabled?: boolean; descriptive_reports_enabled?: boolean; live_autoedit_enabled?: boolean }",
        "export interface AutonomyConfigResponse extends OkResponse { autonomy?: AutonomyStatus }",
        "export interface AutonomyStreamResponse { status: AutonomyStatus; events?: AutonomyEvent[] }",
        "export interface MultimodalStreamResponse { ts: number; status: MultimodalStatus }",
        "",
        "export interface ControlContracts {",
    ]
    for path in sorted(paths):
        operations = paths.get(path) or {}
        for method in sorted(operations):
            upper = method.upper()
            response_type = CONTROL_RESPONSE_TYPES.get((upper, path), "JsonRecord")
            request_type = CONTROL_REQUEST_TYPES.get((upper, path), "never")
            lines.append(
                f"  \"{upper} {path}\": {{ method: \"{upper}\"; path: \"{path}\"; request: {request_type}; response: {response_type} }};"
            )
    lines.extend(
        [
            "}",
            "",
            "export type ControlOperation = keyof ControlContracts;",
            "export type ControlGetOperation = { [P in ControlOperation]: ControlContracts[P][\"method\"] extends \"GET\" ? P : never }[ControlOperation];",
            "export type ControlPostOperation = { [P in ControlOperation]: ControlContracts[P][\"method\"] extends \"POST\" ? P : never }[ControlOperation];",
            "export type ControlResponse<P extends ControlOperation> = ControlContracts[P][\"response\"];",
            "export type ControlRequest<P extends ControlOperation> = ControlContracts[P][\"request\"];",
            "export type PathParams = Record<string, string | number | boolean | null | undefined>;",
            "export type JsonRequester = <T>(url: string, init?: RequestInit) => Promise<T>;",
            "",
            "export class ControlContractClient {",
            "  constructor(private readonly baseUrl: string, private readonly requestJson: JsonRequester) {}",
            "",
            "  async get<P extends ControlGetOperation>(operation: P, params?: PathParams): Promise<ControlResponse<P>> {",
            "    return this.requestJson<ControlResponse<P>>(this.url(operation, params), { method: \"GET\" });",
            "  }",
            "",
            "  async post<P extends ControlPostOperation>(operation: P, body?: ControlRequest<P>, params?: PathParams): Promise<ControlResponse<P>> {",
            "    return this.requestJson<ControlResponse<P>>(this.url(operation, params), {",
            "      method: \"POST\",",
            "      body: JSON.stringify(body ?? {}),",
            "    });",
            "  }",
            "",
            "  stream(operation: ControlGetOperation, params?: PathParams): EventSource {",
            "    return new EventSource(this.url(operation, params));",
            "  }",
            "",
            "  private url(operation: ControlOperation, params?: PathParams): string {",
            "    let resolved = String(operation).replace(/^[A-Z]+\\s+/, \"\");",
            "    for (const [key, value] of Object.entries(params || {})) {",
            "      resolved = resolved.replace(`{${key}}`, encodeURIComponent(String(value ?? \"\")));",
            "    }",
            "    return `${this.baseUrl}${resolved}`;",
            "  }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated contract differs from committed file.")
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    output = root / "vortex-chat" / "public" / "contracts" / "control-openapi.json"
    ts_output = root / "vortex-chat" / "contracts.generated.ts"
    app = create_control_app(ControlDependencies.from_state(_StubState()))
    openapi = app.openapi()
    rendered = json.dumps(openapi, ensure_ascii=True, indent=2) + "\n"
    rendered_ts = _render_control_ts(openapi)
    if args.check:
        current = output.read_text(encoding="utf-8") if output.exists() else ""
        if current != rendered:
            raise SystemExit(f"contract drift: {output}")
        current_ts = ts_output.read_text(encoding="utf-8") if ts_output.exists() else ""
        if current_ts != rendered_ts:
            raise SystemExit(f"contract drift: {ts_output}")
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    ts_output.write_text(rendered_ts, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
