// Generated by scripts/export_contracts.py. Do not edit by hand.
import type {
  AutonomyEvent,
  AutonomyStatus,
  ControlStatus,
  TrainingRunSummary,
} from "./types";

export type JsonRecord = Record<string, unknown>;
export interface OkResponse { ok: boolean; [key: string]: unknown }
export interface HealthResponse extends OkResponse { service?: string; ts?: number }
export interface BootstrapRequest { force?: boolean; mode?: "ensure" | "rebuild" | string }
export interface BootstrapResponse extends OkResponse { started?: boolean; reason?: string; mode?: string; stage?: string; log_path?: string }
export interface InitModelResponse extends OkResponse { started?: boolean }
export interface AllowlistRequest { domains: string[] }
export interface AllowlistResponse extends OkResponse { domains: string[] }
export interface TrainingStartRequest { mode: "quick" | "full" | string; source?: string }
export interface TrainingStartResponse extends OkResponse { run_id?: string; status?: string; queue_reason?: string | null; reused?: boolean; error?: string }
export interface TrainingResetRequest { clear_runs?: boolean; clear_learning_queue?: boolean }
export interface TrainingResetResponse extends OkResponse { removed_runs?: number; runs?: TrainingRunSummary[]; autonomy?: AutonomyStatus }
export interface TrainingRunsResponse extends OkResponse { runs: TrainingRunSummary[] }
export interface TrainingRunResponse extends OkResponse { run: TrainingRunSummary }
export interface TrainingRunEventsResponse extends OkResponse { run_id: string; events: NonNullable<TrainingRunSummary["events"]> }
export interface TrainingRunLogsResponse extends OkResponse { run_id: string; logs: Record<string, string[]> }
export interface TrainingStreamResponse { ts: number; [key: string]: unknown }
export interface ControlAutonomyStatusResponse extends OkResponse { autonomy: AutonomyStatus }
export interface AutonomyToggleResponse extends OkResponse { enabled?: boolean }
export interface AutonomyConfigRequest { enabled?: boolean; reflection_enabled?: boolean; training_enabled?: boolean; autoedit_enabled?: boolean; multi_agent_dialogue_enabled?: boolean; descriptive_reports_enabled?: boolean; live_autoedit_enabled?: boolean }
export interface AutonomyConfigResponse extends OkResponse { autonomy?: AutonomyStatus }
export interface AutonomyStreamResponse { status: AutonomyStatus; events?: AutonomyEvent[] }

export interface ControlContracts {
  "POST /control/autonomy/config": { method: "POST"; path: "/control/autonomy/config"; request: AutonomyConfigRequest; response: AutonomyConfigResponse };
  "POST /control/autonomy/start": { method: "POST"; path: "/control/autonomy/start"; request: never; response: AutonomyToggleResponse };
  "GET /control/autonomy/status": { method: "GET"; path: "/control/autonomy/status"; request: never; response: ControlAutonomyStatusResponse };
  "POST /control/autonomy/stop": { method: "POST"; path: "/control/autonomy/stop"; request: never; response: AutonomyToggleResponse };
  "GET /control/autonomy/stream": { method: "GET"; path: "/control/autonomy/stream"; request: never; response: AutonomyStreamResponse };
  "POST /control/bootstrap": { method: "POST"; path: "/control/bootstrap"; request: BootstrapRequest; response: BootstrapResponse };
  "POST /control/instructions/reload": { method: "POST"; path: "/control/instructions/reload"; request: never; response: OkResponse };
  "GET /control/internet/allowlist": { method: "GET"; path: "/control/internet/allowlist"; request: never; response: AllowlistResponse };
  "POST /control/internet/allowlist": { method: "POST"; path: "/control/internet/allowlist"; request: AllowlistRequest; response: AllowlistResponse };
  "POST /control/model/init": { method: "POST"; path: "/control/model/init"; request: never; response: InitModelResponse };
  "POST /control/runtime/restart": { method: "POST"; path: "/control/runtime/restart"; request: never; response: OkResponse };
  "GET /control/status": { method: "GET"; path: "/control/status"; request: never; response: ControlStatus };
  "POST /control/training/reset": { method: "POST"; path: "/control/training/reset"; request: TrainingResetRequest; response: TrainingResetResponse };
  "GET /control/training/runs": { method: "GET"; path: "/control/training/runs"; request: never; response: TrainingRunsResponse };
  "GET /control/training/runs/{run_id}": { method: "GET"; path: "/control/training/runs/{run_id}"; request: never; response: TrainingRunResponse };
  "GET /control/training/runs/{run_id}/events": { method: "GET"; path: "/control/training/runs/{run_id}/events"; request: never; response: TrainingRunEventsResponse };
  "GET /control/training/runs/{run_id}/logs": { method: "GET"; path: "/control/training/runs/{run_id}/logs"; request: never; response: TrainingRunLogsResponse };
  "POST /control/training/start": { method: "POST"; path: "/control/training/start"; request: TrainingStartRequest; response: TrainingStartResponse };
  "GET /control/training/stream": { method: "GET"; path: "/control/training/stream"; request: never; response: TrainingStreamResponse };
  "GET /healthz": { method: "GET"; path: "/healthz"; request: never; response: HealthResponse };
}

export type ControlOperation = keyof ControlContracts;
export type ControlGetOperation = { [P in ControlOperation]: ControlContracts[P]["method"] extends "GET" ? P : never }[ControlOperation];
export type ControlPostOperation = { [P in ControlOperation]: ControlContracts[P]["method"] extends "POST" ? P : never }[ControlOperation];
export type ControlResponse<P extends ControlOperation> = ControlContracts[P]["response"];
export type ControlRequest<P extends ControlOperation> = ControlContracts[P]["request"];
export type PathParams = Record<string, string | number | boolean | null | undefined>;
export type JsonRequester = <T>(url: string, init?: RequestInit) => Promise<T>;

export class ControlContractClient {
  constructor(private readonly baseUrl: string, private readonly requestJson: JsonRequester) {}

  async get<P extends ControlGetOperation>(operation: P, params?: PathParams): Promise<ControlResponse<P>> {
    return this.requestJson<ControlResponse<P>>(this.url(operation, params), { method: "GET" });
  }

  async post<P extends ControlPostOperation>(operation: P, body?: ControlRequest<P>, params?: PathParams): Promise<ControlResponse<P>> {
    return this.requestJson<ControlResponse<P>>(this.url(operation, params), {
      method: "POST",
      body: JSON.stringify(body ?? {}),
    });
  }

  stream(operation: ControlGetOperation, params?: PathParams): EventSource {
    return new EventSource(this.url(operation, params));
  }

  private url(operation: ControlOperation, params?: PathParams): string {
    let resolved = String(operation).replace(/^[A-Z]+\s+/, "");
    for (const [key, value] of Object.entries(params || {})) {
      resolved = resolved.replace(`{${key}}`, encodeURIComponent(String(value ?? "")));
    }
    return `${this.baseUrl}${resolved}`;
  }
}
